# Generated by Django 4.0.4 on 2022-09-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room/')),
                ('title', models.CharField(max_length=64, verbose_name='제목')),
                ('price', models.CharField(max_length=64, verbose_name='가격')),
                ('select_home', models.CharField(max_length=64, verbose_name='집유형')),
                ('location', models.CharField(max_length=200, verbose_name='위치')),
                ('smaller_period', models.CharField(max_length=64, verbose_name='최소기간')),
                ('startDay', models.CharField(max_length=64, verbose_name='시작일')),
                ('lastDay', models.CharField(max_length=64, verbose_name='종료일')),
                ('floor_space', models.CharField(max_length=64, verbose_name='평수')),
                ('bathroom', models.CharField(max_length=64, verbose_name='욕실수')),
                ('room', models.CharField(max_length=64, verbose_name='방수')),
                ('bed', models.CharField(max_length=64, verbose_name='침대수')),
                ('basic_info', models.CharField(max_length=64, verbose_name='기본정보')),
                ('option', models.CharField(max_length=64, verbose_name='옵션')),
                ('description', models.CharField(max_length=500, verbose_name='설명')),
                ('heart', models.IntegerField(verbose_name='위시')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'db_table': 'host_home',
            },
        ),
    ]
