# Generated by Django 4.1 on 2022-09-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anli", "0002_wish"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wish",
        ),
    ]
