# Generated by Django 4.1 on 2022-08-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64, verbose_name="아이디")),
                ("password", models.CharField(max_length=64, verbose_name="비밀번호")),
                ("nickname", models.CharField(max_length=64, verbose_name="닉네임")),
                ("ph", models.CharField(max_length=64, verbose_name="전화번호")),
                ("email", models.CharField(max_length=64, verbose_name="이메일")),
                ("account_name", models.CharField(max_length=64, verbose_name="예금주")),
                ("account_bank", models.CharField(max_length=64, verbose_name="은행명")),
                ("account", models.CharField(max_length=64, verbose_name="계좌번호")),
                (
                    "registered_dttm",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록시간"),
                ),
            ],
            options={
                "db_table": "test_user",
            },
        ),
    ]
